name: solum_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  product_feature:
    git:
      url: https://github.com/nam-svh/product-feature.git
      ref: main
  checout_feature:
    git:
      url: https://github.com/nam-svh/checkout-feature.git
      ref: main
  go_router: ^13.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
